# PROYECTO1 - ATAQUE DE TIBURONES

In [2]:
%pip install xlrd

Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.13/site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import xlrd as xlrd

In [3]:
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"

proyect_sharks = pd.read_excel(url)

In [4]:
proyect_sharks.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,10th January,2026.0,Unprovoked,Australia,NSW,Avalon Beach,Surfing,Paul Stanton,M,?,...,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,...,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3rd January,2026.0,Unprovoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,...,Unknown,Andy Currie: Province Sud:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
proyect_sharks.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [7]:
proyect_sharks.shape

(7065, 23)

In [8]:
proyect_sharks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7065 entries, 0 to 7064
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7065 non-null   object
 1   Year            7063 non-null   float64
 2   Type            7047 non-null   object
 3   Country         7015 non-null   object
 4   State           6578 non-null   object
 5   Location        6498 non-null   object
 6   Activity        6480 non-null   object
 7   Name            6846 non-null   object
 8   Sex             6486 non-null   object
 9   Age             4070 non-null   object
 10  Injury          7030 non-null   object
 11  Fatal Y/N       6504 non-null   object
 12  Time            3538 non-null   object
 13  Species         3934 non-null   object
 14  Source          7045 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [9]:
proyect_sharks.describe()

              Year  original order
count  7063.000000     6799.000000
mean   1935.890981     3401.152081
std     270.825801     1963.076319
min       0.000000        2.000000
25%    1948.000000     1701.500000
50%    1986.000000     3401.000000
75%    2010.000000     5100.500000
max    2026.000000     6802.000000

In [10]:
proyect_sharks.describe(include="object")

,Date,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,...,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,Unnamed: 21,Unnamed: 22
count,7065,7047,7015,6578,6498,6480,6846,6486,4070,7030,...,3538,3934,7045,6799,6794,6796,6798,6797,1,2
unique,6107,13,251,944,4611,1609,5785,10,251,4179,...,469,1736,5399,6789,6784,6776,6777,6775,1,2
top,1957,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,FATAL,...,Afternoon,White shark,"K. McMurray, TrackingSharks.com",1907.10.16.R-HongKong.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2021.07.23,2012.09.02.b,stopped here,Teramo
freq,9,5217,2578,1192,191,1143,679,5665,92,863,...,215,194,131,2,2,4,2,2,1,1

In [11]:
proyect_sharks.nunique()

Date              6107
Year               261
Type                13
Country            251
State              944
Location          4611
Activity          1609
Name              5785
Sex                 10
Age                251
Injury            4179
Fatal Y/N           12
Time               469
Species           1736
Source            5399
pdf               6789
href formula      6784
href              6776
Case Number       6777
Case Number.1     6775
original order    6797
Unnamed: 21          1
Unnamed: 22          2
dtype: int64

In [12]:
countries_counts = proyect_sharks['Country'].value_counts()
countries_counts

Country
USA                   2578
AUSTRALIA             1482
SOUTH AFRICA           597
NEW ZEALAND            144
PAPUA NEW GUINEA       136
                      ...
GRAND CAYMAN             1
ST. MAARTIN              1
US Virgin Islands        1
GULF OF ADEN             1
CEYLON (SRI LANKA)       1
Name: count, Length: 251, dtype: int64

In [13]:
fatal_attack = proyect_sharks['Fatal Y/N'].value_counts()
fatal_attack

Fatal Y/N
N          4926
Y          1486
UNKNOWN      71
 N            7
F             5
M             3
n             1
Nq            1
2017          1
Y x 2         1
N             1
y             1
Name: count, dtype: int64

In [6]:
usa_counts = proyect_sharks.loc[proyect_sharks['Country'] == 'USA']
usa_counts

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9th December,2025.0,Provoked,USA,Hawaii West Coast Big Island,"Ka'alu""alu Beach",Freeing trapped shark,Josiah Kaimani Ventura,M,24,...,Black Tip Reef Shark,Hawaii News Now:Diver.Net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,5th November,2025.0,Unprovoked,USA,Hawaii,Pine Trees Hanalei Bay Kaui,Swimming,Chance Swanson,M,?,...,Unknown,James Kingsley: Andy Currie: Beat of Hawaii:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5th November,2025.0,Unprovoked,USA,Texas,Matagorda Beach Matagorda,Fishing,Chuck Bledsoe,M,?,...,Not stgated,Christofer Eskander: The Bay City Tribune:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7012,Before 1958,0.0,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",Standing,Horton Chase,M,NaN,...,NaN,"V.M. Coppleson (1956), p.255; R.F. Hutton",ND-0056-HortonChase.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0056,ND.0056,54.0,NaN,NaN
7046,Before 1921,0.0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,NaN,...,NaN,"T. Helm, p.219",ND-0019-Kelley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0019,ND.0019,20.0,NaN,NaN
7051,Before 17-Jul-1916,0.0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,NaN,...,NaN,"C. Creswell, GSAF; Wilmington Star, 7/17/1916",ND-0014-pre1916-NorthCarolina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0014,ND.0014,15.0,NaN,NaN
7055,Circa 1862,0.0,Unprovoked,USA,Hawaii,Puna,NaN,"A ""chiefess""",F,NaN,...,NaN,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11.0,NaN,NaN
7062,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN

In [7]:
usa_counts["Year"].value_counts()

Year
2015.0    73
2017.0    67
2007.0    66
2014.0    65
2016.0    65
          ..
1779.0     1
1751.0     1
1640.0     1
1642.0     1
1000.0     1
Name: count, Length: 190, dtype: int64

In [8]:
#Trabajaremos con los datos registrados en Estados Unidos, a partir del año
usa_counts1 = usa_counts[usa_counts['Year'].between(2000,2026)]
usa_counts1

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9th December,2025.0,Provoked,USA,Hawaii West Coast Big Island,"Ka'alu""alu Beach",Freeing trapped shark,Josiah Kaimani Ventura,M,24,...,Black Tip Reef Shark,Hawaii News Now:Diver.Net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,5th November,2025.0,Unprovoked,USA,Hawaii,Pine Trees Hanalei Bay Kaui,Swimming,Chance Swanson,M,?,...,Unknown,James Kingsley: Andy Currie: Beat of Hawaii:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5th November,2025.0,Unprovoked,USA,Texas,Matagorda Beach Matagorda,Fishing,Chuck Bledsoe,M,?,...,Not stgated,Christofer Eskander: The Bay City Tribune:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2796,26-Mar-2000,2000.0,Unprovoked,USA,Florida,"Juno Beach, Palm Beach County",Boogie boarding,Heather Van Olst,F,14,...,1.8 m [6'] shark,"Stuart News, 3/28/2000; Jupiter Couier, 3/29/2000",2000.03.26-VanOlst.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.03.26,2000.03.26,4265.0,NaN,NaN
2797,24-Mar-2000,2000.0,Unprovoked,USA,Florida,"Floridana Beach, Brevard County",Surfing,Barry Pasonski,M,37,...,1.2 m [4'] shark,"Orlando Sentinel, 3/25/2000, p.D.3",2000.03.24-Pasonski.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.03.24,2000.03.24,4264.0,NaN,NaN
2804,Mar-2000,2000.0,Unprovoked,USA,Louisiana,Midnight Lump (38 miles offshore),Spearfishing,Kurt Bickel,M,39,...,"Shortfin mako shark, 3 m to 3.4 m [10' to 11']","R. Collier, GSAF",2000.03.00.a-Bickel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.03.00,2000.03.00,4257.0,NaN,NaN
2805,21-Feb-2000,2000.0,Unprovoked,USA,Florida,"Riviera Beach, Palm Beach County",NaN,male,M,27,...,NaN,"The Palm Beach Post, 2/22/2000",2000.02.21-male-Riviera Beach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.02.21,2000.02.21,4256.0,NaN,NaN
2812,2000,2000.0,Watercraft,USA,Florida,"Boca Grande, Lee County",Fishing for tarpon,"boat: occupant, Terry Winters",M,NaN,...,Hammerhead shark,"B. Stout, News-Press, 7/2/2005",2000.00.00-BocaGrandeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.00.00,2000.00.00,4249.0,NaN,NaN

In [9]:
#Se muestran los estados donde mayor episodios de ataques de tiburones hubo, en formato descendiente.  
usa_counts1["State"] = usa_counts1['State'].str.strip()
print (usa_counts1['State'].value_counts(normalize=True).head(5) * 100)

State
Florida           51.409496
Hawaii            12.982196
California        10.905045
South Carolina     7.047478
North Carolina     5.786350
Name: proportion, dtype: float64

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\2134854473.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1["State"] = usa_counts1['State'].str.strip()

In [10]:
correcciones = {
    'M': 'M',
    'F': 'F',
    'M ': 'M', # Por si acaso
    'lli': 'M', # Suponiendo que 'lli' era una 'M' mal escrita
    'm': 'M'
}
usa_counts1['Sex'] = usa_counts1['Sex'].map(correcciones)

usa_counts1["Sex"] = usa_counts1['Sex'].str.strip()
print (usa_counts1['Sex'].value_counts(normalize=True) * 100)

Sex
M    76.34981
F    23.65019
Name: proportion, dtype: float64

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\549289030.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1['Sex'] = usa_counts1['Sex'].map(correcciones)
C:\Users\HP\AppData\Local\Temp\ipykernel_11320\549289030.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1["Sex"] = usa_counts1['Sex'].str.strip()

In [11]:
usa_counts1['Age'] = pd.to_numeric(usa_counts1['Age'], errors='coerce')
bins = [0, 12, 18, 35, 60, 100]
labels = ['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']

usa_counts1['Age_Group'] = pd.cut(usa_counts1['Age'], bins=bins, labels=labels)
print(usa_counts1['Age_Group'].value_counts(normalize=True) * 100)

Age_Group
Young Adult    33.301158
Adult          26.833977
Teen           21.042471
Child          13.996139
Senior          4.826255
Name: proportion, dtype: float64

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\2480516378.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1['Age'] = pd.to_numeric(usa_counts1['Age'], errors='coerce')
C:\Users\HP\AppData\Local\Temp\ipykernel_11320\2480516378.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1['Age_Group'] = pd.cut(usa_counts1['Age'], bins=bins, labels=labels)

In [12]:
top_5 = usa_counts1['Activity'].value_counts().head(5).index
usa_counts1['Activity'] = usa_counts1['Activity'].where(usa_counts1['Activity'].isin(top_5), 'Other')
print(usa_counts1['Activity'].value_counts(normalize=True) * 100)

Activity
Other       37.212750
Surfing     34.618236
Swimming    15.344700
Wading       5.782061
Fishing      3.928836
Standing     3.113417
Name: proportion, dtype: float64

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\429770182.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1['Activity'] = usa_counts1['Activity'].where(usa_counts1['Activity'].isin(top_5), 'Other')

In [13]:
usa_counts1.isna().sum()

Date                 0
Year                 0
Type                 8
Country              0
State                1
Location             9
Activity             0
Name                12
Sex                 34
Age                313
Injury               1
Fatal Y/N           64
Time               231
Species            522
Source               3
pdf                103
href formula       105
href               105
Case Number        103
Case Number.1      103
original order     103
Unnamed: 21       1348
Unnamed: 22       1349
Age_Group          313
dtype: int64

In [14]:
usa_counts1.head(5)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Age_Group
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55.0,...,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,NaN,...,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9th December,2025.0,Provoked,USA,Hawaii West Coast Big Island,"Ka'alu""alu Beach",Other,Josiah Kaimani Ventura,M,24.0,...,Hawaii News Now:Diver.Net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Young Adult
10,5th November,2025.0,Unprovoked,USA,Hawaii,Pine Trees Hanalei Bay Kaui,Swimming,Chance Swanson,M,NaN,...,James Kingsley: Andy Currie: Beat of Hawaii:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5th November,2025.0,Unprovoked,USA,Texas,Matagorda Beach Matagorda,Fishing,Chuck Bledsoe,M,NaN,...,Christofer Eskander: The Bay City Tribune:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
usa_counts1.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22', 'Age_Group'],
      dtype='object')

In [16]:
usa_counts1.drop(["Source", "pdf", "href formula", "href", "Case Number", "Case Number.1", "original order", "Unnamed: 21", "Unnamed: 22"], axis=1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\1063360112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1.drop(["Source", "pdf", "href formula", "href", "Case Number", "Case Number.1", "original order", "Unnamed: 21", "Unnamed: 22"], axis=1, inplace=True)

In [17]:
usa_counts1.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Age_Group'],
      dtype='object')

In [18]:
usa_counts1.head(5)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Age_Group
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55.0,Taken by shark body recovered with multiple in...,Y,1200hrs,Great White Shark,Adult
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,NaN,Hand Injury,N,0800hrs,Suspected Great White Shark,NaN
5,9th December,2025.0,Provoked,USA,Hawaii West Coast Big Island,"Ka'alu""alu Beach",Other,Josiah Kaimani Ventura,M,24.0,Bite wounds to thigh,N,1630hrs,Black Tip Reef Shark,Young Adult
10,5th November,2025.0,Unprovoked,USA,Hawaii,Pine Trees Hanalei Bay Kaui,Swimming,Chance Swanson,M,NaN,Injuries to legs,N,Mid afternoon,Unknown,NaN
11,5th November,2025.0,Unprovoked,USA,Texas,Matagorda Beach Matagorda,Fishing,Chuck Bledsoe,M,NaN,Laceration on top and undermeath right foot,N,Not stated,Not stgated,NaN

In [19]:
usa_counts1.drop("Date", axis=1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\2577449430.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1.drop("Date", axis=1, inplace=True)

In [20]:
usa_counts1.drop("Time", axis=1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_11320\951194094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa_counts1.drop("Time", axis=1, inplace=True)

In [22]:
usa_counts1.head()

,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Species,Age_Group
3,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55.0,Taken by shark body recovered with multiple in...,Y,Great White Shark,Adult
4,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,NaN,Hand Injury,N,Suspected Great White Shark,NaN
5,2025.0,Provoked,USA,Hawaii West Coast Big Island,"Ka'alu""alu Beach",Other,Josiah Kaimani Ventura,M,24.0,Bite wounds to thigh,N,Black Tip Reef Shark,Young Adult
10,2025.0,Unprovoked,USA,Hawaii,Pine Trees Hanalei Bay Kaui,Swimming,Chance Swanson,M,NaN,Injuries to legs,N,Unknown,NaN
11,2025.0,Unprovoked,USA,Texas,Matagorda Beach Matagorda,Fishing,Chuck Bledsoe,M,NaN,Laceration on top and undermeath right foot,N,Not stgated,NaN

In [ ]:
#prueba